// <auto-generated />
using CoreReactRedux.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CoreReactRedux.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreReactRedux.Models.DataClassChild", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.Property<int>("ParentId");

                    b.HasKey("ChildId");

                    b.HasIndex("ParentId");

                    b.ToTable("DataClassChildTable");
                });

            modelBuilder.Entity("CoreReactRedux.Models.DataClassParent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Data");

                    b.HasKey("ParentId");

                    b.ToTable("DataClassParentTable");
                });

            modelBuilder.Entity("CoreReactRedux.Models.DataClassChild", b =>
                {
                    b.HasOne("CoreReactRedux.Models.DataClassParent", "DataClassParent")
                        .WithMany("DataClassChildList")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
